# Generated by Django 4.0.3 on 2022-05-03 15:16

import core.models
from django.db import migrations, models
import versatileimagefield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('image', versatileimagefield.fields.VersatileImageField(blank=True, null=True, upload_to=core.models.Image.get_file_path, verbose_name='Image')),
                ('image_ppoi', versatileimagefield.fields.PPOIField(blank=True, default='0.5x0.5', editable=False, max_length=20, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
