# Generated by Django 4.0.3 on 2022-05-03 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_corefile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CoreFile',
        ),
    ]
