# Generated by Django 4.0.3 on 2022-05-26 19:15

from django.db import migrations, models
import django_minio_backend.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_delete_corefile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('file', models.FileField(null=True, storage=django_minio_backend.models.MinioBackend(bucket_name='contents'), upload_to=django_minio_backend.models.iso_date_prefix)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
