# Generated by Django 4.0.3 on 2022-05-26 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='chat_code',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
