# Generated by Django 4.0.3 on 2022-05-26 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_content'),
        ('chat', '0002_alter_message_image_alter_message_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='message', to='core.content'),
        ),
    ]
