# Generated by Django 4.0.3 on 2022-05-03 18:52

from django.db import migrations, models
import django_minio_backend.models


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0002_alter_artpiece_cover_alter_artpiece_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artpiece',
            name='url',
        ),
        migrations.AddField(
            model_name='artpiece',
            name='file',
            field=models.FileField(null=True, storage=django_minio_backend.models.MinioBackend(bucket_name='art-pieces'), upload_to=django_minio_backend.models.iso_date_prefix),
        ),
    ]
