# Generated by Django 4.0.3 on 2022-05-06 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0003_remove_artpiece_url_artpiece_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artpiece',
            name='title',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
    ]
