# Generated by Django 4.0.3 on 2022-05-06 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0004_alter_artpiece_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artpiece',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
